const products = [
    {
        _id: 1001,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315397/spfOne_rmfy5h.webp",
        productName: "Cap for Boys",
        price: "35.00",
        color: "Blank and White",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
    {
        _id: 1002,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315399/spfTwo_i3oybf.webp",
        productName: "Tea Table",
        price: "180.00",
        color: "Gray",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1003,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315398/spfThree_dt8k96.webp",
        productName: "Headphones",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1004,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315397/spfFour_nywb78.webp",
        productName: "Sun glasses",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1005,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315358/bestSellerOne_iguqem.webp",
        productName: "Flower Base",
        price: "35.00",
        color: "Blank and White",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1006,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315358/bestSellerFour_jaaqhz.webp",
        productName: "New Backpack",
        price: "180.00",
        color: "Gray",
        badge: false,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1007,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315431/newArrThree_iihoow.webp",
        productName: "Household materials",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1008,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315358/bestSellerTwo_pwlttt.webp",
        productName: "Travel Bag",
        price: "220.00",
        color: "Black",
        badge: false,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1009,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315430/newArrOne_kj9rks.webp",
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1010,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315431/newArrTwo_s6ec2w.webp",
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1011,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315358/bestSellerThree_shw6m3.webp",
        productName: "cloth Basket",
        price: "80.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1012,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315430/newArrFour_l9wo8j.webp",
        productName: "Funny toys for babies",
        price: "60.00",
        color: "Mixed",
        badge: false,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1013,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315397/spfOne_rmfy5h.webp",
        productName: "Cap for Boys",
        price: "35.00",
        color: "Blank and White",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
    {
        _id: 1014,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315399/spfTwo_i3oybf.webp",
        productName: "Tea Table",
        price: "180.00",
        color: "Gray",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1015,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315398/spfThree_dt8k96.webp",
        productName: "Headphones",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1016,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315397/spfFour_nywb78.webp",
        productName: "Sun glasses",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1017,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315358/bestSellerOne_iguqem.webp",
        productName: "Flower Base",
        price: "35.00",
        color: "Blank and White",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      {
        _id: 1018,
        img: "https://res.cloudinary.com/deyn4wssy/image/upload/v1730315358/bestSellerFour_jaaqhz.webp",
        productName: "New Backpack",
        price: "180.00",
        color: "Gray",
        badge: false,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      },
      
  
];
module.exports = products;